name: Delete Artifact Workflow

on:
  workflow_run:
    workflows: ["Test Workspace"]
    types:
      - completed

jobs:
  delete-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Artifacts
        run: |
          # Retrieve and delete artifacts using GitHub API
          ARTIFACTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts" \
            | jq -r '.artifacts[].id')

          for ARTIFACT_ID in $ARTIFACTS; do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}"
          done
