name: Check if I can free space
on: push

jobs:
  build:
    name: Foo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]
    steps:
    - uses: actions/checkout@v2
      with:
          lfs: "true"
          submodules: "recursive"   
    - name: checkout with git lfs
      run: git lfs checkout
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    - name: Bar
      run: |
        echo "Free space:"
        df -h  
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Bar
      run: |
        echo "Free space:"
        df -h
