name: My build action requiring more space
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:

      - name: Check free space 1
        run: |
          echo "Free space:"
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check free space 2
        run: |
          echo "Free space:"
          df -h
