name: Test Workspace
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create File
        run: echo "This is a file" > my-file.txt

      - name: Echo LS
        run: ls -halt

      - name: Persist Workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: ./

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Restore Workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Echo LS
        run: ls -halt

      - name: Display File
        run: cat my-file.txt

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact

      - name: Echo LS
        run: ls -halt

      - name: Restore Workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
