name: Check if I can free space
on: push

jobs:
  build:
    name: Foo
    runs-on: ubuntu-latest
    steps:

      - name: Bar
        run: |
          echo "Free space:"
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          echo "Free space:"
          df -h
