name: Check if I can free space
on: push

jobs:
  build:
    name: Foo
    runs-on: ubuntu-latest
    steps:
    
        
    - name: Bar
      run: |
        echo "Free space:"
        df -h
        
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
        
    - name: Bar
      run: |
        echo "Free space:"
        df -h
